y<-read.table("Test.txt", header = TRUE, sep = ";")
z<-rbind(subset(x, Date == "1/2/2007"), subset(x, Date == "2/2/2007"))
z<-transform(z, DateTime = paste(Date, Time))
z<-transform(z,DateTime = strptime(DateTime, "%d/%m/%Y %H:%M:%S"))
b<-c(0,8)
a<-range(z$DateTime)
c<-as.numeric(as.character(z$Global_active_power))
png(filename = "C:/R/Exploratory Data Analysis/Project 1/Plot2.png", width = 480, height = 480, units = "px")
plot(a,b, xlab = "", ylab = "Global Active Power")
lines(z$DateTime, c , pch = "0")
dev.off()